config/routes.rb
Rails.application.routes.draw do
  resources :txes, only: %i[new create]
  resources :commodities, only: %i[index new create show]
  get 'spash/index'
  devise_for :users
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root 'commodities#index'
end

app/models/commodity.rb
class Commodity < ApplicationRecord
  mount_uploader :icon, PictureUploader
  belongs_to :user
  has_many :txes, dependent: :destroy

  validates_presence_of :name, :icon, :user_id
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commodity, only: %i[show edit update destroy]

  # GET /commodities or /commodities.json
  def index
    @commodities = Commodity.all.where(user_id: current_user.id).order('created_at DESC')
  end

  # GET /commodities/1 or /commodities/1.json
  def show
    @commodity = Commodity.find_by(id: params[:id])
    @commodities = Commodity.all
    @txes = Tx.all.where(commodity_id: @commodity.id).order('created_at DESC')
    @amount = @txes.all.where(user_id: current_user.id).sum(:amount)
  end

  # GET /commodities/new
  def new
    @commodity = Commodity.new
  end

  # GET /commodities/1/edit
  def edit; end

  # POST /commodities or /commodities.json
  def create
    @commodity = Commodity.new(commodity_params)

    respond_to do |format|
      if @commodity.save
        format.html { redirect_to commodities_url, notice: 'Commodity was successfully created.' }
        format.json { render :show, status: :created, location: @commodity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @commodity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commodities/1 or /commodities/1.json
  def update
    respond_to do |format|
      if @commodity.update(commodity_params)
        format.html { redirect_to commodity_url(@commodity), notice: 'Commodity was successfully updated.' }
        format.json { render :show, status: :ok, location: @commodity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @commodity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commodities/1 or /commodities/1.json
  def destroy
    @commodity.destroy

    respond_to do |format|
      format.html { redirect_to commodities_url, notice: 'Commodity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_commodity
    @commodity = Commodity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def commodity_params
    params.require(:commodity).permit(:name, :icon, :user_id)
  end
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/views/commodities/_commodity.html.erb
<div id="<%= dom_id commodity %>">
  <p>
    <strong>Name:</strong>
    <%= commodity.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= commodity.icon %>
  </p>

  <p>
    <strong>User:</strong>
    <%= commodity.user_id %>
  </p>

</div>

app/views/commodities/_form.html.erb
<section class='form-new-commodity'>
<%= form_with(model: commodity) do |form| %>
  <% if commodity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(commodity.errors.count, "error") %> prohibited this commodity from being saved:</h2>

      <ul>
        <% commodity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
  <%= form.label :icon, style: "display: block" %>
  <%= form.file_field :icon %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</section>

app/views/commodities/edit.html.erb
<h1>Editing commodity</h1>

<%= render "form", commodity: @commodity %>

<br>

<div>
  <%= link_to "Show this commodity", @commodity %> |
  <%= link_to "Back to commodities", commodities_path %>
</div>

app/views/commodities/index.html.erb
<section class='commodity-section'>
<p style="color: green"><%= notice %></p>
  <div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="#">Account Settings</a>
    <a href="#">Merchant Finder</a>
    <a href="#">Claim promo</a>
    <a href="#">Share promo</a>
  </div>
  <div class='header'>
    <div onclick="openNav()">
      <%= image_tag ("hamburger.png") %>
    </div>
    <div>
      <h1>Categories</h1>     
    </div>
    <div class='search-section'>
      <%= image_tag ("search2.png"), class:'search-image' %>
    </div>
  </div>
  
  <div class="commodities">    
      <% if @commodities.length == 0 %>
         <p>There are no categories</p>
         <% else %>
         <div class='commodity-cards'>
      <% @commodities.each do |commodity| %>
        <%= link_to commodity_path(commodity.id) do%>
          <div class='commodity-card'>
            <div><%= image_tag(commodity.icon_url, width: 100, height: 100) if commodity.icon.present? %></div>
            <div class='commodity-details'>
              <div><small>Name: <%= commodity.name %></small></div>
              <div><small>Count: <%= commodity.txes.count %></small></div>
              <div><small><%= commodity.created_at.strftime("%d %b %Y") %></small></div>
            </div>
          </div>
        <% end %>
        <% end %>
      </div>
        <% end %>
  
    <div class='green-button-section'>
      <% if can? :create, Commodity %>
        <%= link_to "New Category", new_commodity_path, class:'new-category-button' %>
      <% end %>
    </div>
  </div>
  </section>

app/views/commodities/new.html.erb
<section class='new-commodity-section'>  
  <div class='header'>
    <div class='back-arrow'>
      <%= link_to '←', commodities_path %>
    </div>
    <div>
       <h1>New Category</h1>
    </div>
    <div class='search-section'>
      <%= image_tag ("search2.png"), class:'search-image' %>
    </div>
  </div>
  <div class="commodities new-commodity-form">
    <div>
      <%= render "form", commodity: @commodity %>
    </div>
    <div class='green-button-section'>
      <%= link_to "Scan", class:'new-category-button' %>
    </div>
  </div>
  </section>

app/views/commodities/show.html.erb
<section class='transaction-section'>
<p style="color: green"><%= notice %></p>
  <div class='header'>
    <div class='back-arrow'>
      <%= link_to '←', commodities_path %>
    </div>
    <div>
      <h1>Transactions</h1>     
    </div>
    <div class='search-section'>
      <%= image_tag ("search2.png"), class:'search-image' %>
    </div>
  </div>  
  <div class="transactions">
      <% if @txes.length == 0 %>
         <p>There are no transactions</p>
         <% else %>
         <div class='transaction-cards'>
         <div style='text-align:center;'><small>Sum: <%= @amount %></div>
      <% @txes.each do |tx| %>
          <div class='transaction-card'>
            <div class='transaction-details'>
              <div><small>Category: <%= tx.commodity.name %></small></div>
              <div><small>Created At:<%= tx.created_at.strftime("%d %b %Y") %></small></div>
              <div><small>Transaction: <%= tx.name %></small></div>
              <div><small>Amount: <%= tx.amount %></small></div>
            </div>
          </div>
        <% end %>
      </div>
        <% end %>
    <div class='green-button-section'>
      <% if can? :create, Tx %>
        <%= link_to "New Transaction", new_tx_path, class:'new-category-button' %>
      <% end %>
    </div>
  </div>
  </section>