config/routes.rb
Rails.application.routes.draw do
  resources :txes, only: %i[new create]
  resources :commodities, only: %i[index new create show]
  get 'spash/index'
  devise_for :users
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root 'commodities#index'
end

app/models/tx.rb
class Tx < ApplicationRecord
  belongs_to :user
  belongs_to :commodity

  validates_presence_of :name, :amount, :commodity_id, :user_id
end

app/controllers/txes_controller.rb
class TxesController < ApplicationController
  before_action :set_tx, only: %i[show edit update destroy]

  # GET /txes or /txes.json
  def index
    @commodity = Commodity.find_by(id: params[:commodity_id])
  end

  # GET /txes/1 or /txes/1.json
  def show; end

  # GET /txes/new
  def new
    @tx = Tx.new
    @commodities = Commodity.all.where(user_id: current_user.id)
    @commodity = Commodity.find_by(id: params[:commodity_id])
  end

  # GET /txes/1/edit
  def edit; end

  # POST /txes or /txes.json
  def create
    @tx = Tx.new(tx_params)
    @commodity = @tx.commodity_id
    @commodities = Commodity.all.where(user_id: current_user.id)
    respond_to do |format|
      if @tx.save
        format.html { redirect_to commodity_url(@commodity), notice: 'Tx was successfully created.' }
        format.json { render :show, status: :created, location: @tx }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /txes/1 or /txes/1.json
  def update
    respond_to do |format|
      if @tx.update(tx_params)
        format.html { redirect_to tx_url(@tx), notice: 'Tx was successfully updated.' }
        format.json { render :show, status: :ok, location: @tx }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /txes/1 or /txes/1.json
  def destroy
    @tx.destroy

    respond_to do |format|
      format.html { redirect_to txes_url, notice: 'Tx was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tx
    @tx = Tx.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tx_params
    params.require(:tx).permit(:author_id, :name, :amount, :user_id, :commodity_id)
  end
end

app/helpers/txes_helper.rb
module TxesHelper
end

app/views/txes/_form.html.erb
<section class='form-new-transaction'>
<%= form_with(model: tx) do |form| %>
  <% if tx.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tx.errors.count, "error") %> prohibited this tx from being saved:</h2>

      <ul>
        <% tx.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :author_id, value: current_user.id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.label :commodity_id, style: "display: block" %>
    <%= form.select :commodity_id, options_for_select(@commodities.map { |commodity| [commodity.name, commodity.id] }) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</section>

app/views/txes/_tx.html.erb
<div id="<%= dom_id tx %>">
  <p>
    <strong>Author:</strong>
    <%= tx.author_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= tx.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= tx.amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tx.user_id %>
  </p>

  <p>
    <strong>Commodity:</strong>
    <%= tx.commodity_id %>
  </p>

</div>

app/views/txes/edit.html.erb
<h1>Editing tx</h1>

<%= render "form", tx: @tx %>

<br>

<div>
  <%= link_to "Show this tx", @tx %> |
  <%= link_to "Back to txes", txes_path %>
</div>

app/views/txes/new.html.erb
<section class='new-transaction-section'>  
  <div class='header'>
    <div class='back-arrow'>
      <%= link_to '←', commodities_path %>
    </div>
    <div>
      <h1>New Transaction</h1>
    </div>
    <div class='search-section'>
      <%= image_tag ("search2.png"), class:'search-image' %>
    </div>
  </div>
  <div class="transactions new-transaction-form">
    <div>
      <%= render "form", tx: @tx %>
    </div>
    <div class='green-button-section'>
      <%= link_to "Scan", class:'new-category-button' %>
    </div>
  </div>
  </section>

app/views/txes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tx %>

<div>
  <%= link_to "Edit this tx", edit_tx_path(@tx) %> |
  <%= link_to "Back to txes", txes_path %>

  <%= button_to "Destroy this tx", @tx, method: :delete %>
</div>